spring:
  liquibase:
    change-log: classpath:/db/db.changelog-master.xml
  application:
    name: blog
  datasource:
    hikari:
      username: admin
      password: qwerty
    url: jdbc:postgresql://localhost:5432/blog_db
  kafka:
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
server:
  port: 8082
logging:
  level:
    org.springframework.transaction: DEBUG
    org.springframework.orm.jpa: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: TRACE
    org.springframework.transaction.interceptor: TRACE
    org.springframework.transaction.support: TRACE

    # SQL запросы и параметры (ОЧЕНЬ важно!)
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.loader.Loader: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    org.hibernate.engine.internal.TwoPhaseLoad: TRACE
    org.hibernate.persister.entity.AbstractEntityPersister: DEBUG


springdoc:
  api-docs:
    path: /api-docs
    enabled: true
    groups:
      enabled: true

  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    display-request-duration: true
    operations-sorter: method
    doc-expansion: none
    filter: true

  show-actuator: true
  packages-to-scan: src.pet.blog.controller
  paths-to-match: /api/**

  cache:
    disabled: false
